---
- name: install git on the ubuntu server
  hosts: all
  become: yes
  tasks:
    - name: install git on ubuntu machine
      ansible.builtin.apt:
        name: git
        update_cache: yes
        state: present

    
