---
- name : install utilities
  hosts : all
  tasks :
    - name : create a file with some dynamic value
      ansible.builtin.template :
        src : info.txt.j2
        dest : /tmp/info.txt




    # - name : install utilities on ubuntu
    #   ansible.builtin.package:
    #     name : "{{ item }}"
    #     state : present
    #   become : yes
    #   loop : "{{ packages }}"
    # - name : debug variables
    #   ansible.builtin.debug:
    #     var: purpose
    # - name : ansible configuration
    #   ansible.builtin.debug:
    #     var : ansible_config_file

      

