---
- name : install utilities
  hosts : all
  tasks :
    - name : install utilities on ubuntu
      ansible.builtin.package:
        name : "{{ item }}"
        state : present
      become : yes
      loop : "{{ packages }}"
    - name : debug variables
      ansible.builtin.debug:
        var: purpose

      

