---
- name: Install Java on Ubuntu
  hosts: all
  become: yes
  vars:
    java_package: openjdk-11-jdk
  tasks:
    - name: install java
      ansible.builtin.apt:
        name: "{{ java_package }}"
        update_cache: yes
        state: present
      notify:
        - installed java
  handlers:
    - name : installed java
      ansible.builtin.debug:
        msg: java is installed