---
- name : Install Utilities
  hosts : all
  vars : 
    utils :
      - git
      - nano
      - tree
  tasks :
    - name : Install Utilities
      ansible.builtin.apt :
        name : "{{ utils }}"
      notify :
        - ensure ssh is running
  handlers :
    name : ensure ssh is running
    ansible.builtin.systemd:
      state: running
